---
- src: git+ssh://git@gitlab.com/alex-shatilov/ansible-roles/ansible-role-grafana.git
  version: v.0.3
  name: grafana

- src: git+ssh://git@gitlab.com/alex-shatilov/ansible-roles/ansible-role-docker.git
  version: v.0.2
  name: docker
